using System;
using System.Collections.Generic;

namespace CoreTest.Entity.Models
{
    public partial class MatchView
    {
        public int Id { get; set; }
        public int? Type { get; set; }
        public string Status { get; set; }
        public int? Gid { get; set; }
        public int? Gidm { get; set; }
        public DateTime? Datetime { get; set; }
        public string League { get; set; }
        public int? GunmH { get; set; }
        public int? GunmC { get; set; }
        public string TeamH { get; set; }
        public string TeamC { get; set; }
        public string Strong { get; set; }
        public int? More { get; set; }
        public string Eventid { get; set; }
        public string Hot { get; set; }
        public string CenterTv { get; set; }
        public string Play { get; set; }
        public int? ScoreH { get; set; }
        public int? ScoreC { get; set; }
        public int? Time { get; set; }
        public int? FScoreH { get; set; }
        public int? FScoreC { get; set; }
        public string FStatus { get; set; }
        public int? ChargeStatus { get; set; }
        public int? Kind { get; set; }
        public int? HScoreH { get; set; }
        public int? HScoreC { get; set; }
        public int? FPointH { get; set; }
        public int? FPointC { get; set; }
        public int? HPointH { get; set; }
        public int? HPointC { get; set; }
        public bool? IsEnable { get; set; }
        public bool? IsEnable2 { get; set; }
        public bool? IsShowGq { get; set; }
        public bool? ShowScoreH { get; set; }
        public bool? ShowScoreC { get; set; }
        public int? HSettlement { get; set; }
        public int? CSettlement { get; set; }
        public DateTime? MatchLastUpdateTime { get; set; }
        public double? IorFhh { get; set; }
        public double? IorFhn { get; set; }
        public double? IorFhc { get; set; }
        public double? IorFnh { get; set; }
        public double? IorFnn { get; set; }
        public double? IorFnc { get; set; }
        public double? IorFch { get; set; }
        public double? IorFcn { get; set; }
        public double? IorFcc { get; set; }
        public DateTime? BcqclastUpdateTime { get; set; }
        public double? IorH1c0 { get; set; }
        public double? IorH2c0 { get; set; }
        public double? IorH2c1 { get; set; }
        public double? IorH3c0 { get; set; }
        public double? IorH3c1 { get; set; }
        public double? IorH3c2 { get; set; }
        public double? IorH4c0 { get; set; }
        public double? IorH4c1 { get; set; }
        public double? IorH4c2 { get; set; }
        public double? IorH4c3 { get; set; }
        public double? IorH0c0 { get; set; }
        public double? IorH1c1 { get; set; }
        public double? IorH2c2 { get; set; }
        public double? IorH3c3 { get; set; }
        public double? IorH4c4 { get; set; }
        public double? IorH0c1 { get; set; }
        public double? IorH0c2 { get; set; }
        public double? IorH1c2 { get; set; }
        public double? IorH0c3 { get; set; }
        public double? IorH1c3 { get; set; }
        public double? IorH2c3 { get; set; }
        public double? IorH0c4 { get; set; }
        public double? IorOvh { get; set; }
        public double? IorH1c4 { get; set; }
        public double? IorH2c4 { get; set; }
        public double? IorH3c4 { get; set; }
        public double? IorOvc { get; set; }
        public DateTime? BdlastUpdateTime { get; set; }
        public string StrOdd { get; set; }
        public string StrEven { get; set; }
        public double? IorEoo { get; set; }
        public double? IorEoe { get; set; }
        public DateTime? DslastUpdateTime { get; set; }
        public string RatioO { get; set; }
        public string RatioU { get; set; }
        public double? IorOuh { get; set; }
        public double? IorOuc { get; set; }
        public string HratioO { get; set; }
        public string HratioU { get; set; }
        public double? IorHouh { get; set; }
        public double? IorHouc { get; set; }
        public double? IorMh { get; set; }
        public double? IorMc { get; set; }
        public double? IorMn { get; set; }
        public double? IorHmh { get; set; }
        public double? IorHmc { get; set; }
        public double? IorHmn { get; set; }
        public string Ratio { get; set; }
        public double? IorRh { get; set; }
        public double? IorRc { get; set; }
        public string Hratio { get; set; }
        public double? IorHrh { get; set; }
        public double? IorHrc { get; set; }
        public double? IorOdd { get; set; }
        public double? IorEven { get; set; }
        public double? IorT01 { get; set; }
        public double? IorT23 { get; set; }
        public double? IorT46 { get; set; }
        public double? IorOver { get; set; }
        public DateTime? ZrqlastUpdateTime { get; set; }
        public int? Dygid { get; set; }
        public int? Rqgid { get; set; }
        public int? Dxgid { get; set; }
        public int? Dsgid { get; set; }
        public int? Bdgid { get; set; }
        public int? Zrqgid { get; set; }
        public int? Bcqcgid { get; set; }
        public string RatioOuho { get; set; }
        public string RatioOuhu { get; set; }
        public double? IorOuho { get; set; }
        public double? IorOuhu { get; set; }
        public string RatioOuco { get; set; }
        public string RatioOucu { get; set; }
        public double? IorOuco { get; set; }
        public double? IorOucu { get; set; }
        public int? Zhgggid { get; set; }
        public string RatioP { get; set; }
        public double? IorPrh { get; set; }
        public double? IorPrc { get; set; }
        public string RatioOp { get; set; }
        public string RatioUp { get; set; }
        public double? IorPouc { get; set; }
        public double? IorPouh { get; set; }
        public double? IorPeoo { get; set; }
        public double? IorPeoe { get; set; }
        public double? IorPo { get; set; }
        public double? IorPe { get; set; }
        public double? IorMhp { get; set; }
        public double? IorMcp { get; set; }
        public double? IorMnp { get; set; }
        public int? MoreP { get; set; }
        public string RatioPouho { get; set; }
        public string RatioPouhu { get; set; }
        public double? IorPouho { get; set; }
        public double? IorPouhu { get; set; }
        public string RatioPouco { get; set; }
        public string RatioPoucu { get; set; }
        public double? IorPouco { get; set; }
        public double? IorPoucu { get; set; }
        public double? IorHmhp { get; set; }
        public double? IorHmcp { get; set; }
        public double? IorHmnp { get; set; }
        public string HratioP { get; set; }
        public double? IorHprh { get; set; }
        public double? IorHprc { get; set; }
        public string HratioOp { get; set; }
        public string HratioUp { get; set; }
        public double? IorHpouh { get; set; }
        public double? IorHpouc { get; set; }
        public DateTime? ZhgglastUpdateTime { get; set; }
    }
}
